#Scan backend + frontend + configs for security vulnerabilities.Will use Sonaqube(SAST)

name: Code Scan

on:
    workflow_call:

jobs:
    code-scan:
        runs-on: self-hosted
        steps:
         - uses: actions/checkout@v3
         - name: Set up Java
           uses: actions/setup-java@v3
           with:
             distribution: 'temurin'
             java-version: '21'

         - name: SonarQube Scan
           run: |
            docker run --rm \
            --platform linux/arm64 \
            -v "${{ github.workspace }}:/usr/src" \
            -w /usr/src \
            sonarsource/sonar-scanner-cli:10.0 \
            -Dsonar.projectKey=springboot-app \
            -Dsonar.projectName=springboot-app \
            -Dsonar.sources=src \
            -Dsonar.host.url=http://localhost:9000 \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}